<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/composer' . '/autoload_real.php';
require_once __DIR__ . '/yiisoft/yii2/PHPExcel/PHPExcel/IOFactory.php';

return ComposerAutoloaderInit0c74ba3f25302d533d05d704ab0f1dcb::getLoader();
